export const CHANGE_CURPAGE = "CHANGE_CURPAGE";
export const CHANGE_EACHPAGES = "CHANGE_EACHPAGES";
export const GET_USER_BY_PAGE = "GET_USER_BY_PAGE";
export const DELETE_USER_BY_ID = "DELETE_USER_BY_ID";