export const GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID";
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_MOVIE_BY_PAGE = "GET_MOVIE_BY_PAGE";
export const GET_MOVIE_TYPE_LIST = "GET_MOVIE_TYPE_LIST";